# Generated by Django 2.2.10 on 2021-09-07 13:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание опроса')),
                ('data_start', models.DateTimeField(editable=False, verbose_name='Дата старта')),
                ('data_end', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст опроса')),
                ('type_q', models.CharField(choices=[('Ответ текстом', 'Ответ текстом'), ('Ответ с выбором одного варианта', 'Ответ с выбором одного варианта'), ('Ответ с выбором нескольких вариантов', 'Ответ с выбором нескольких вариантов')], default='Ответ текстом', max_length=40)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollsModel', verbose_name='Опрос')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.QuestionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.ChoiceModel', verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.QuestionModel', verbose_name='Вопрос')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
